# Generated by Django 2.2.28 on 2023-06-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainsample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testing67', models.SmallIntegerField()),
                ('level78', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
